spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: documentation-platform
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/documentation_platform}
    username: ${SPRING_DATASOURCE_USERNAME:documentation}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  graphql:
    path: /api/graphql
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
